config:
  aws:region: us-east-1
  aws:profile: default
  wdwebsolutions-aws-foundation:expectedAccountId: "767688909304"
  wdwebsolutions-aws-foundation:verificationDomain: wdwebsolutions.com
  wdwebsolutions-aws-foundation:activateCostAllocationTags: false
